version: 2
updates:
    - package-ecosystem: "npm"
      directory: "/"
      schedule:
          interval: "weekly"
      commit-message:
          prefix: "depbot: "
      reviewers:
          - "bawerbozdag"
      assignees:
          - "bawerbozdag"
      labels:
          - "dependencies"
      groups:
          security-updates:
              applies-to: security-updates
              patterns:
                  - "*"
          minor-updates:
              applies-to: version-updates
              patterns:
                  - "*"
              update-types:
                  - "minor"
                  - "patch"