name: Build Check

on:
    push:
        branches: [master]
    pull_request:

jobs:
    build:
        runs-on: ubuntu-22.04

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: "npm"

            - name: Install dependencies
              run: npm install

            - name: Run Build
              run: npm run build

            - name: Check dist folder exists
              run: |
                  if [ ! -d dist ]; then
                    echo "❌ 'dist/' folder not found after build."
                    exit 1
                  fi
