name: Vitest - Tailwind v3 Tests

on:
    push:
        paths:
            - "__tests__/tailwind_v3/**"
            - "src/**"
    pull_request:
        paths:
            - "__tests__/tailwind_v3/**"
            - "src/**"

jobs:
    test-v3:
        name: Run Tailwind v3 Tests
        runs-on: ubuntu-22.04

        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: "npm"
                  cache-dependency-path: "__tests__/tailwind_v3/package-lock.json"

            - name: Install dependencies
              working-directory: __tests__/tailwind_v3
              run: npm ci

            - name: Link src for tests
              run: ln -s ../../../src __tests__/tailwind_v3/src

            - name: Run tests
              working-directory: __tests__/tailwind_v3
              run: npm test
