name: Vitest Tests

on:
    push:
        paths:
            - "**"
    pull_request:
        paths:
            - "**"

jobs:
    install:
        name: Install Dependencies
        runs-on: ubuntu-22.04

        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                  node-version: "20"
                  cache: "npm"
                  cache-dependency-path: "package-lock.json"

            - name: Install dependencies
              run: npm ci

    test-v3:
        name: Tailwind v3 Tests
        runs-on: ubuntu-22.04
        needs: install

        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                  node-version: 20.x
                  cache: "npm"

            - name: Install v3 test dependencies
              run: |
                  cd __tests__/tailwind_v3
                  npm ci
                  npm test

    test-v4:
        name: Tailwind v4 Tests
        runs-on: ubuntu-22.04
        needs: [install, test-v3]

        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                  node-version: 20.x
                  cache: "npm"

            - name: Install v4 test dependencies
              run: |
                  cd __tests__/tailwind_v4
                  npm ci
                  npm test
